<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Lukas.Qto.Desktop</AssemblyName>
    <RootNamespace>Lukas.Qto.Desktop</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../THEKIE.Qto.Core/THEKIE.Qto.Core.csproj" />
  </ItemGroup>
</Project>
