import assert from "node:assert/strict";
import test from "node:test";
import {chromium,expect} from "@playwright/test";

async function openExport(page){
 const button=page.getByRole("button",{name:"내보내기 화면 열기",exact:true});
 if(!await button.isVisible())await page.getByLabel("도면 업무 더보기",{exact:true}).click();
 await button.click();
}

test("prepared delivery retains its revision, recipient and stage after editing a new revision",{skip:!process.env.DELIVERY_PREVIEW_ORIGIN,timeout:60000},async()=>{
 const origin=new URL(process.env.DELIVERY_PREVIEW_ORIGIN);assert.ok(["localhost","127.0.0.1"].includes(origin.hostname));
 const browser=await chromium.launch({headless:true});
 try{
  const page=await browser.newPage();const errors=[];page.on("pageerror",e=>errors.push(e.message));
  await page.addInitScript(()=>{
   if(sessionStorage.getItem("1hk:preview:review:00000000-0000-4000-8000-000000000111"))return;
   const target={id:"delivery-shape",kind:"사각형",page:1,x:120,y:120,name:"납품 기준 영역",layer:"review",color:"#6650f5",lineWidth:"0.25 mm",fill:"없음",text:""};
   sessionStorage.setItem("1hk:preview:review:00000000-0000-4000-8000-000000000111",JSON.stringify({phase:"approved",role:"author",revision:1,page:1,position:0,before:0,issue:"",message:"R1 확인",focused:false,compared:false,history:[],target}));
  });
  await page.goto(`${origin.origin}/workspace-preview/drawing-workspace?layout=pdf&startKind=office&screenDocument=00000000-0000-4000-8000-000000000111&returnProject=00000000-0000-4000-8000-000000000101`);
  await openExport(page);
  await page.getByRole("button",{name:"납품 구성으로 계속",exact:true}).click();
  let delivery=page.getByRole("region",{name:"납품·수신 화면 예시",exact:true});
  await delivery.getByRole("combobox",{name:/수신 대상 예시/}).selectOption({label:"현장 담당 · 예시"});
  await delivery.getByRole("button",{name:"납품 준비 화면 보기",exact:true}).click();
  await delivery.getByRole("button",{name:"도면으로 돌아가기",exact:true}).click();
  await page.getByRole("button",{name:"새 개정 시작",exact:true}).click();
  await page.getByRole("button",{name:"납품 기준 영역 · 화면 도형",exact:true}).click();
  await page.getByRole("textbox",{name:"이름",exact:true}).fill("R2 수정 영역");
  await openExport(page);
  await expect(delivery.getByRole("heading",{name:"납품 준비 중 · 화면 예시",exact:true})).toBeVisible();
  await expect(delivery.getByText("R1 · 1쪽 · 납품 기준 영역",{exact:true})).toBeVisible();
  await expect(delivery.getByText("R2 · 1쪽 · R2 수정 영역",{exact:true})).toHaveCount(0);
  await delivery.getByRole("button",{name:"실패 상태 체험",exact:true}).click();
  await delivery.getByRole("button",{name:"같은 구성으로 재시도",exact:true}).click();
  await delivery.getByRole("button",{name:"수신자 화면 보기",exact:true}).click();
  await expect(delivery.getByText(/현장 담당 · 예시의 보기 전용/)).toBeVisible();
  await expect(delivery.getByText("R1 · 1쪽 · 납품 기준 영역",{exact:true})).toBeVisible();
  await page.reload();
  await openExport(page);
  await expect(delivery.getByRole("heading",{name:"수신자 화면 예시",exact:true})).toBeVisible();
  await expect(delivery.getByText(/현장 담당 · 예시의 보기 전용/)).toBeVisible();
  await expect(delivery.getByText("R1 · 1쪽 · 납품 기준 영역",{exact:true})).toBeVisible();
  if(process.env.DELIVERY_PREVIEW_SCREENSHOT)await page.screenshot({path:process.env.DELIVERY_PREVIEW_SCREENSHOT,fullPage:true,animations:"disabled"});
  await page.getByRole("button",{name:"현재 도면으로 새 납품 구성",exact:true}).click();
  await page.getByRole("button",{name:"납품 구성으로 계속",exact:true}).click();
  await expect(delivery.getByText("R2 · 1쪽 · R2 수정 영역",{exact:true})).toBeVisible();
  await page.getByText("이전 납품 구성 (1)",{exact:true}).click();
  const history=page.getByRole("region",{name:"이전 납품 구성 목록",exact:true});
  await history.getByText("구성 1 · R1 · 현장 담당 · 예시",{exact:true}).click();
  await expect(history.getByText("R1 · 1쪽 · 납품 기준 영역",{exact:true})).toBeVisible();
  await expect(history.locator("input,select,textarea")).toHaveCount(0);
  const url=page.url();
  const key="1hk:preview:delivery:00000000-0000-4000-8000-000000000101:00000000-0000-4000-8000-000000000111";
  await page.evaluate(key=>{const original=Storage.prototype.setItem;window.restoreDeliveryWrite=()=>{Storage.prototype.setItem=original;};Storage.prototype.setItem=function(name,value){if(name===key)throw Error("test quota");return original.call(this,name,value);};},key);
  await delivery.getByRole("combobox",{name:/수신 대상 예시/}).selectOption({label:"협력사 담당 · 예시"});
  await expect(page.getByRole("alert").filter({hasText:"납품 초안을 보관하지 못했습니다"})).toBeVisible();
  await page.getByRole("button",{name:"Close",exact:true}).click();
  await openExport(page);
  await expect(delivery.getByRole("combobox",{name:/수신 대상 예시/})).toHaveValue("협력사 담당 · 예시");
  await page.evaluate(()=>window.restoreDeliveryWrite());
  await page.getByRole("button",{name:"납품 초안 보관 다시 시도",exact:true}).click();
  await expect(page.getByRole("alert").filter({hasText:"납품 초안을 보관하지 못했습니다"})).toHaveCount(0);
  await page.reload();
  await openExport(page);
  await expect(delivery.getByRole("combobox",{name:/수신 대상 예시/})).toHaveValue("협력사 담당 · 예시");
  await page.getByText("이전 납품 구성 (1)",{exact:true}).click();
  await history.getByText("구성 1 · R1 · 현장 담당 · 예시",{exact:true}).click();
  await expect(history.getByText("R1 · 1쪽 · 납품 기준 영역",{exact:true})).toBeVisible();
  await page.getByRole("button",{name:"현재 도면으로 새 납품 구성",exact:true}).click();
  await page.getByRole("radio",{name:/DWG 변환 엔진 미연결/}).check();
  await page.getByRole("button",{name:"납품 구성으로 계속",exact:true}).click();
  await expect(history.getByText("구성 2 · R2 · 협력사 담당 · 예시",{exact:true})).toBeVisible();
  await history.getByText("구성 2 · R2 · 협력사 담당 · 예시",{exact:true}).click();
  await expect(history.getByText("R2 · 1쪽 · R2 수정 영역",{exact:true})).toBeVisible();
  await expect(history.getByText("R1 · 1쪽 · 납품 기준 영역",{exact:true})).toBeVisible();
  let stored=await page.evaluate(key=>sessionStorage.getItem(key),key);
  const records=JSON.parse(stored).deliveryHistory;assert.equal(records.length,2);assert.notEqual(records[0].id,records[1].id);
  assert.equal(records[0].exportSelection.format,"pdf");assert.equal(records[1].exportSelection.format,"pdf");
  await expect(delivery.getByText("DWG",{exact:true})).toBeVisible();
  if(process.env.DELIVERY_HISTORY_SCREENSHOT)await page.screenshot({path:process.env.DELIVERY_HISTORY_SCREENSHOT,fullPage:true,animations:"disabled"});
  await page.getByRole("button",{name:"Close",exact:true}).click();
  await page.getByRole("link",{name:"작업공간으로 돌아가기",exact:true}).click();
  await page.getByRole("link",{name:"납품",exact:true}).click();
  const projectDelivery=page.getByRole("region",{name:"프로젝트 납품 구성",exact:true});
  const documentCard=projectDelivery.locator('[data-document-id="00000000-0000-4000-8000-000000000111"]');
  await expect(documentCard.locator(":scope > dl").getByText("R2 · 1쪽 · R2 수정 영역",{exact:true})).toBeVisible();
  await documentCard.getByText("이전 납품 구성 (2)",{exact:true}).click();
  await documentCard.getByText("구성 1 · R1 · 현장 담당 · 예시",{exact:true}).click();
  await expect(documentCard.getByText("R1 · 1쪽 · 납품 기준 영역",{exact:true})).toBeVisible();
  if(process.env.PROJECT_DELIVERY_SCREENSHOT)await page.screenshot({path:process.env.PROJECT_DELIVERY_SCREENSHOT,fullPage:true,animations:"disabled"});
  await documentCard.getByRole("link",{name:"납품 작업 이어가기",exact:true}).click();
  await expect(delivery.getByText("DWG",{exact:true})).toBeVisible();
  await page.getByRole("button",{name:"Close",exact:true}).click();
  await page.getByRole("link",{name:"작업공간으로 돌아가기",exact:true}).click();
  await expect(page).toHaveURL(/panel=project-deliveries/);
  stored=await page.evaluate(key=>sessionStorage.getItem(key),key);
  await page.goto(`${url}&role=viewer`);
  await openExport(page);
  await expect(delivery.getByRole("combobox",{name:/수신 대상 예시/})).toBeDisabled();
  assert.equal(await page.evaluate(key=>sessionStorage.getItem(key),key),stored);
  await page.goto(url.replace("screenDocument=00000000-0000-4000-8000-000000000111","screenDocument=00000000-0000-4000-8000-000000000112"));
  await openExport(page);
  await expect(page.getByRole("button",{name:"납품 구성으로 계속",exact:true})).toBeVisible();
  await expect(delivery).toHaveCount(0);
  await page.evaluate(key=>sessionStorage.setItem(key,"null"),key);
  await page.goto(url);
  await openExport(page);
  await expect(page.getByRole("alert").filter({hasText:"납품 초안을 복원하지 못했습니다"})).toBeVisible();
  await expect(page.getByRole("button",{name:"납품 구성으로 계속",exact:true})).toHaveCount(0);
  assert.equal(await page.evaluate(key=>sessionStorage.getItem(key),key),"null");
  await page.goto(`${origin.origin}/workspace-preview?project=00000000-0000-4000-8000-000000000101&panel=project-deliveries`);
  await expect(projectDelivery.getByRole("alert")).toContainText("일부 도면의 납품 구성을 읽지 못했습니다");
  await page.evaluate(({key,stored})=>sessionStorage.setItem(key,stored),{key,stored});
  await projectDelivery.getByRole("button",{name:"납품 목록 다시 읽기",exact:true}).click();
  await expect(documentCard.getByText("현재 납품 초안 · 구성 시점 기준",{exact:true})).toBeVisible();
  assert.equal(await page.evaluate(key=>sessionStorage.getItem(key),key),stored);
  assert.deepEqual(errors,[]);
 }finally{await browser.close();}
});
