import assert from "node:assert/strict";
import test from "node:test";
import { chromium, expect } from "@playwright/test";
import { PDFDocument } from "pdf-lib";

// Explicit opt-in: uses an isolated browser, never the user's current tab.
test("PDF recovery keeps page and review, and replacement cancel preserves the original", {skip:!process.env.PDF_RECOVERY_ORIGIN,timeout:90000}, async()=>{
  const origin=new URL(process.env.PDF_RECOVERY_ORIGIN);
  assert.ok(["localhost","127.0.0.1"].includes(origin.hostname));
  const doc=await PDFDocument.create();
  doc.addPage([600,400]);doc.addPage([600,400]);
  const buffer=Buffer.from(await doc.save());
  const file={name:"recovery-check.pdf",mimeType:"application/pdf",buffer};
  const browser=await chromium.launch({headless:true});
  let page;
  const errors=[];
  const failedRequests=[];
  try {
    page=await browser.newPage();
    page.on("pageerror",e=>errors.push(e.message));
    page.on("requestfailed",request=>failedRequests.push({url:request.url(),error:request.failure()?.errorText}));
    await page.goto(`${origin.origin}/workspace-preview?project=00000000-0000-4000-8000-000000000101&start=file`);
    await page.getByLabel("작업실에서 열 PDF 선택").setInputFiles(file);
    await page.getByRole("button",{name:"선택한 PDF 등록 방식 확인",exact:true}).click();
    await page.getByRole("button",{name:"등록 방식 확인 후 준비",exact:true}).click();
    await expect(page.getByRole("button",{name:"다음 페이지",exact:true})).toBeEnabled();
    await page.getByRole("button",{name:"다음 페이지",exact:true}).click();
    await page.getByRole("button",{name:"검토 화면 열기",exact:true}).click();
    await page.getByRole("button",{name:"문 위치 변경 체험",exact:true}).click();
    await page.getByRole("textbox",{name:/요청 내용/}).fill("2쪽 원본 복구 회귀 확인");
    await page.getByRole("button",{name:"검토 요청",exact:true}).click();
    await expect(page.getByRole("heading",{name:"검토 대기",exact:true})).toBeVisible();
    await page.reload();
    await expect(page.getByRole("button",{name:"검토 모드",exact:true})).toHaveAttribute("aria-pressed","true");
    await page.getByLabel("로컬 PDF 선택",{exact:true}).setInputFiles({...file,name:"renamed.pdf"});
    await expect(page.getByText("동일한 PDF 원본을 확인했습니다. 현재 페이지와 검토 기록을 유지합니다.",{exact:true})).toBeVisible();
    await expect(page.getByRole("heading",{name:"검토 대기",exact:true})).toBeVisible();
    await expect(page.getByRole("region",{name:"도면 검토 패널",exact:true})).toContainText("2쪽 원본 복구 회귀 확인");
    await expect(page.getByRole("button",{name:"다음 페이지",exact:true})).toBeDisabled();
    await expect(page.getByRole("button",{name:"이전 페이지",exact:true})).toBeEnabled();
    const other=await PDFDocument.create();other.addPage();
    const dialog=page.waitForEvent("dialog");
    await page.getByLabel("로컬 PDF 선택",{exact:true}).setInputFiles({...file,buffer:Buffer.from(await other.save())});
    const confirmation=await dialog;
    assert.equal(confirmation.type(),"confirm");
    await confirmation.dismiss();
    await expect(page.getByRole("heading",{name:"renamed.pdf",exact:true})).toBeVisible();
    await expect(page.getByRole("heading",{name:"검토 대기",exact:true})).toBeVisible();
    await page.getByRole("button",{name:"검토자 보기",exact:true}).click();
    await page.getByRole("button",{name:"변경 전후 확인",exact:true}).click();
    await page.getByRole("button",{name:"검토 완료 · 승인 요청",exact:true}).click();
    await expect(page.getByRole("heading",{name:"검토 완료 · 승인 대기",exact:true})).toBeVisible();
    const replacementDialog=page.waitForEvent("dialog");
    await page.getByLabel("로컬 PDF 선택",{exact:true}).setInputFiles({...file,buffer:Buffer.from(await other.save())});
    await (await replacementDialog).accept();
    await expect(page.getByRole("heading",{name:"작성 중",exact:true})).toBeVisible();
    await expect(page.getByRole("button",{name:"작성 모드",exact:true})).toHaveAttribute("aria-pressed","true");
    await expect(page.getByRole("button",{name:"사각형 도구 화면",exact:true})).toBeEnabled();
    await page.getByRole("button",{name:"사각형 도구 화면",exact:true}).click();
    await page.getByRole("region",{name:"화면 도형 오버레이",exact:true}).click({position:{x:100,y:100}});
    await expect(page.getByRole("button",{name:"사각형 01 · 화면 도형",exact:true})).toBeVisible();
    await page.reload();
    await expect(page.getByRole("button",{name:"검토 모드",exact:true})).toHaveAttribute("aria-pressed","true");
    await page.getByLabel("로컬 PDF 선택",{exact:true}).setInputFiles(file);
    await expect(page.getByRole("heading",{name:"검토 완료 · 승인 대기",exact:true})).toBeVisible();
    await expect(page.getByRole("button",{name:"이전 페이지",exact:true})).toBeEnabled();
    assert.deepEqual(errors,[]);
    await page.getByLabel("도면 업무 더보기",{exact:true}).click();
    await page.getByRole("button",{name:"물량·내역 화면 열기",exact:true}).click();
    await page.getByRole("button",{name:"설명용 A01 예시 보기",exact:true}).click();
    await page.getByRole("button",{name:"3 내역",exact:true}).click();
    await page.getByRole("button",{name:"자재·발주·입고 화면 보기",exact:true}).click();
    await page.getByRole("button",{name:"현재 페이지·개정을 자재 근거로 지정",exact:true}).click();
    const documentId=new URL(page.url()).searchParams.get("screenDocument");assert.ok(documentId);
    await page.goto(`${origin.origin}/workspace-preview?project=00000000-0000-4000-8000-000000000101&panel=project-materials&sourceDrawing=${documentId}`);
    await expect(page.getByRole("region",{name:"자재 지정 근거",exact:true})).toContainText("지정 근거: R1 · 2쪽");
    await page.getByText("지정 근거 열기",{exact:true}).click();
    const reader=page.getByRole("region",{name:"지정 PDF 읽기 전용 열람",exact:true});
    await reader.getByLabel("지정 원본 PDF 다시 선택",{exact:true}).setInputFiles({...file,buffer:Buffer.from(await other.save())});
    await expect(reader.getByRole("alert")).toContainText("다른 PDF");
    await expect(reader.locator("canvas")).toHaveCount(0);
    await reader.getByLabel("지정 원본 PDF 다시 선택",{exact:true}).setInputFiles({...file,name:"same-original-renamed.pdf"});
    await expect(reader.getByText("지정된 2쪽 · 페이지 고정",{exact:true})).toBeVisible();
    await expect(reader.locator("canvas")).toBeVisible();
    await expect(reader.getByRole("button",{name:"자료 다음 페이지",exact:true})).toHaveCount(0);
    assert.deepEqual(errors,[]);
  } catch(error) {
    const screen=page&&!page.isClosed()?await page.locator('body').innerText().catch(()=>"화면 읽기 실패"):"브라우저 종료";
    console.error('PDF recovery diagnostics:',JSON.stringify({url:page?.url(),errors,failedRequests,screen:screen.slice(0,7000)}));
    throw error;
  } finally {await browser.close();}
});
