import assert from "node:assert/strict";
import test from "node:test";
import {chromium,expect} from "@playwright/test";

test("change round returns from its fixed drawing and carries cost checks into a frozen report",{skip:!process.env.CHANGE_PREVIEW_ORIGIN,timeout:60000},async()=>{
 const origin=new URL(process.env.CHANGE_PREVIEW_ORIGIN);assert.ok(["localhost","127.0.0.1"].includes(origin.hostname));
 const browser=await chromium.launch({headless:true});
 try{
  const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on("pageerror",e=>errors.push(e.message));
  const base=`${origin.origin}/workspace-preview?project=00000000-0000-4000-8000-000000000101`;
  await page.goto(base);
  await page.getByRole("link",{name:"1층 평면도 작업실 열기",exact:true}).click();
  await page.getByRole("button",{name:"검토 화면 열기",exact:true}).click();
  await page.getByRole("button",{name:"문 위치 변경 체험",exact:true}).click();
  await page.getByRole("textbox",{name:/요청 내용/}).fill("변경 보고서 연결 검토");
  await page.getByRole("button",{name:"검토 요청",exact:true}).click();
  await expect(page.getByRole("heading",{name:"검토 대기",exact:true})).toBeVisible();
  await page.goto(`${base}&panel=project-changes`);
  await page.getByRole("textbox",{name:"변경 이름",exact:true}).fill("출입구 변경");
  await page.getByRole("textbox",{name:"변경 사유",exact:true}).fill("출입구 유효폭 확인 및 내역 검토");
  await page.getByRole("checkbox",{name:/1층 평면도 · R1/}).check();
  await page.getByRole("button",{name:"변경 회차를 이 탭에 보관",exact:true}).click();
  const round=page.locator('[id^="change-round-"]');
  await expect(round).toHaveCount(1);
  const roundId=(await round.getAttribute("id")).replace("change-round-","");
  await round.getByRole("link",{name:"R1 검토 기록 읽기 전용으로 열기",exact:true}).click();
  await expect(page.getByRole("button",{name:"문 위치 변경 체험",exact:true})).toHaveCount(0);
  await page.getByRole("link",{name:"변경 이력으로 돌아가기",exact:true}).click();
  await expect(page).toHaveURL(new RegExp(`changeRound=${roundId}`));
  await expect(round).toBeFocused();
  const addition=round.getByRole("combobox",{name:"추가 공사의 내역 누락",exact:true});
  await addition.focus();await addition.selectOption("applied");
  await expect(addition).toBeFocused();
  for(const [index,kind,item] of [[1,"항목 추가","방화문 신설"],[2,"항목 제외","기존 문 철거 항목 제외"],[3,"단위·단가 기준 수정","문 설치 단위 수정"]]){
    await round.getByRole("button",{name:`${kind} 변경안 작성`,exact:true}).click();
    const proposal=round.getByRole("listitem",{name:`내역 변경안 ${index}`,exact:true});
    await proposal.getByRole("textbox",{name:"내역 항목명",exact:true}).fill(item);
    await proposal.getByRole("textbox",{name:"단위",exact:true}).fill("개");
    await proposal.getByRole("textbox",{name:"변경 사유·기준",exact:true}).fill("출입구 변경 근거 확인");
  }
  const firstProposal=round.getByRole("listitem",{name:"내역 변경안 1",exact:true});
  await page.evaluate(()=>{const original=Storage.prototype.setItem;window.restoreCostWrite=()=>{Storage.prototype.setItem=original;};Storage.prototype.setItem=function(key,value){if(key==="1hk:preview:changes:00000000-0000-4000-8000-000000000101")throw Error("test quota");return original.call(this,key,value);};});
  await firstProposal.getByRole("textbox",{name:"내역 항목명",exact:true}).fill("보관 실패 변경안");
  await addition.selectOption("checked");
  await page.getByRole("navigation",{name:"프로젝트 업무"}).getByRole("link",{name:"검토",exact:true}).click();
  await expect(page.getByRole("alert").filter({hasText:"입력을 보호하기 위해 이동을 멈췄습니다"})).toBeVisible();
  await expect(page.getByRole("heading",{name:"프로젝트 변경 이력",exact:true})).toBeVisible();
  await expect(firstProposal.getByRole("textbox",{name:"내역 항목명",exact:true})).toHaveValue("보관 실패 변경안");
  await page.getByText("변경 이력 보고서 · 납품 구성 예시",{exact:true}).click();
  await page.getByRole("button",{name:"현재 회차 전체 선택",exact:true}).click();
  await expect(page.getByRole("button",{name:"구성 확인 · 예시 기록 남기기",exact:true})).toBeDisabled();
  await page.evaluate(()=>window.restoreCostWrite());
  await page.getByRole("button",{name:"변경안 보관 다시 시도",exact:true}).click();
  await expect(page.getByRole("button",{name:"구성 확인 · 예시 기록 남기기",exact:true})).toBeDisabled();
  await page.getByRole("button",{name:"점검 보관 다시 시도",exact:true}).click();
  await expect(page.getByRole("button",{name:"구성 확인 · 예시 기록 남기기",exact:true})).toBeEnabled();
  await firstProposal.getByRole("textbox",{name:"내역 항목명",exact:true}).fill("방화문 신설");
  await addition.selectOption("applied");
  await firstProposal.getByRole("link",{name:"변경안의 도면 근거 보기",exact:true}).click();
  await page.getByRole("link",{name:"변경 이력으로 돌아가기",exact:true}).click();
  await expect(firstProposal.getByRole("textbox",{name:"내역 항목명",exact:true})).toHaveValue("방화문 신설");
  await page.getByText("변경 이력 보고서 · 납품 구성 예시",{exact:true}).click();
  await page.getByRole("button",{name:"현재 회차 전체 선택",exact:true}).click();
  await page.getByRole("combobox",{name:"보고서 형식",exact:true}).selectOption("xlsx");
  await page.getByRole("textbox",{name:"수신자 예시",exact:true}).fill("감리 검토 예시");
  await page.getByRole("button",{name:"구성 확인 · 예시 기록 남기기",exact:true}).click();
  const report=page.getByRole("heading",{name:"보고서 구성 1 · XLSX · 미발송",exact:true}).locator('..');
  await expect(report).toContainText("1층 평면도 R1 1쪽");
  await expect(report).toContainText("추가 공사의 내역 누락 반영 · 예시");
  await expect(report).toContainText("방화문 신설");
  await expect(report).toContainText("기존 문 철거 항목 제외");
  await expect(report).toContainText("문 설치 단위 수정");
  await firstProposal.getByRole("textbox",{name:"내역 항목명",exact:true}).fill("현재 변경안 수정");
  await expect(report).not.toContainText("현재 변경안 수정");
  await addition.selectOption("unchecked");
  await expect(report).toContainText("추가 공사의 내역 누락 반영 · 예시");
  await page.reload();
  await page.getByText("변경 이력 보고서 · 납품 구성 예시",{exact:true}).click();
  await expect(report).toContainText("감리 검토 예시");
  await expect(report).toContainText("추가 공사의 내역 누락 반영 · 예시");
  await expect(addition).toHaveValue("unchecked");
  if(process.env.CHANGE_REPORT_SCREENSHOT)await page.screenshot({path:process.env.CHANGE_REPORT_SCREENSHOT,fullPage:true,animations:"disabled"});
  await page.goto(`${base}&panel=project-changes&role=viewer`);
  await expect(page.getByRole("textbox",{name:"변경 이름",exact:true})).toHaveCount(0);
  await expect(addition).toBeDisabled();
  await expect(firstProposal.getByRole("textbox",{name:"내역 항목명",exact:true})).toBeDisabled();
  await page.getByText("변경 이력 보고서 · 납품 구성 예시",{exact:true}).click();
  await expect(page.getByRole("button",{name:"구성 확인 · 예시 기록 남기기",exact:true})).toBeDisabled();
  assert.deepEqual(errors,[]);
 }finally{await browser.close();}
});
