import assert from "node:assert/strict";
import test from "node:test";
import {chromium,expect} from "@playwright/test";
import {PDFDocument} from "pdf-lib";

test("cancelled invitations reject guests and reissued links preserve the frozen resource",{skip:!process.env.SHARING_PREVIEW_ORIGIN,timeout:60000},async()=>{
 const origin=new URL(process.env.SHARING_PREVIEW_ORIGIN);assert.ok(["localhost","127.0.0.1"].includes(origin.hostname));
 const browser=await chromium.launch({headless:true});
 try{
  const page=await browser.newPage();const errors=[];page.on("pageerror",e=>errors.push(e.message));
  const base=`${origin.origin}/workspace-preview?project=00000000-0000-4000-8000-000000000101`;
  await page.goto(`${base}&panel=project-resources`);
  await page.getByRole("textbox",{name:"자료 이름",exact:true}).fill("재발급 회의록");
  await page.getByRole("textbox",{name:"자료 설명",exact:true}).fill("최초 공유 내용");
  await page.getByRole("button",{name:"자료 목록에 보관 · 이 탭",exact:true}).click();
  await page.getByRole("navigation",{name:"프로젝트 업무"}).getByRole("link",{name:"외부 공유",exact:true}).click();
  await page.getByRole("textbox",{name:"수신자 표시 이름",exact:true}).fill("발주처 예시");
  await page.getByLabel("만료일",{exact:true}).fill("2099-01-01");
  await page.getByRole("checkbox",{name:/재발급 회의록/}).check();
  await page.getByRole("button",{name:"공유 범위 고정 · 이 탭에 보관",exact:true}).click();
  const oldHref=await page.getByRole("link",{name:"외부 참여자 화면 체험",exact:true}).getAttribute("href");
  await page.getByText("초대 관리 · 로컬 예시",{exact:true}).click();
  await page.getByRole("button",{name:"초대 취소",exact:true}).click();
  await page.getByRole("button",{name:"계속 유지",exact:true}).click();
  await expect(page.getByText("상태: 사용 가능 · 로컬 예시",{exact:true})).toBeVisible();
  await page.getByRole("button",{name:"초대 취소",exact:true}).click();
  await page.evaluate(()=>{const original=Storage.prototype.setItem;window.restoreInvitationWrite=()=>{Storage.prototype.setItem=original;};Storage.prototype.setItem=function(key,value){if(key.startsWith("1hk:preview:sharing:"))throw Error("보관 실패 예시");return original.call(this,key,value);};});
  await page.getByRole("button",{name:"초대 취소 확인",exact:true}).click();
  await expect(page.getByRole("alert")).toContainText("보관 실패 예시");
  await expect(page.getByText("상태: 사용 가능 · 로컬 예시",{exact:true})).toBeVisible();
  await page.evaluate(()=>window.restoreInvitationWrite());
  await page.getByRole("button",{name:"초대 취소 확인",exact:true}).click();
  await expect(page.getByText("상태: 취소됨",{exact:true})).toBeVisible();
  await page.goto(`${origin.origin}${oldHref}`);
  await expect(page.getByRole("alert")).toContainText("취소된 초대");
  await expect(page.getByRole("textbox",{name:"이름 예시",exact:true})).toHaveCount(0);
  await page.evaluate(()=>{const key="1hk:preview:resources:00000000-0000-4000-8000-000000000101";const rows=JSON.parse(sessionStorage.getItem(key));rows[0].note="공유 이후 바뀐 내부 내용";sessionStorage.setItem(key,JSON.stringify(rows));});
  await page.goto(`${base}&panel=project-sharing`);
  await page.getByText("초대 관리 · 로컬 예시",{exact:true}).click();
  await page.getByLabel("재발급 만료일",{exact:true}).fill("2099-02-01");
  await page.getByRole("button",{name:"새 링크로 재발급",exact:true}).click();
  const links=page.getByRole("link",{name:"외부 참여자 화면 체험",exact:true});
  await expect(links).toHaveCount(2);
  const newHref=await links.first().getAttribute("href");assert.notEqual(newHref,oldHref);
  await page.goto(`${origin.origin}${newHref}`);
  await page.getByRole("textbox",{name:"이름 예시",exact:true}).fill("외부 예시");
  await page.getByRole("textbox",{name:"소속 예시",exact:true}).fill("발주처");
  await page.getByRole("button",{name:"공유된 범위 열기",exact:true}).click();
  await expect(page.getByRole("article")).toContainText("최초 공유 내용");
  await expect(page.getByRole("article")).not.toContainText("공유 이후 바뀐 내부 내용");
  await page.goto(`${base}&panel=project-sharing&role=viewer`);
  await expect(page.getByText("초대 관리 · 로컬 예시",{exact:true})).toHaveCount(0);
  assert.deepEqual(errors,[]);
 }finally{await browser.close();}
});

test("invitation draft restores its scope after navigation and reload without creating an invitation",{skip:!process.env.SHARING_PREVIEW_ORIGIN,timeout:60000},async()=>{
 const browser=await chromium.launch({headless:true});
 try{
  const page=await browser.newPage();const errors=[];page.on("pageerror",e=>errors.push(e.message));
  const origin=new URL(process.env.SHARING_PREVIEW_ORIGIN);assert.ok(["localhost","127.0.0.1"].includes(origin.hostname));
  const base=`${origin.origin}/workspace-preview?project=00000000-0000-4000-8000-000000000101`;
  await page.goto(`${base}&panel=project-resources`);
  await page.getByRole("textbox",{name:"자료 이름",exact:true}).fill("초대 범위 회의록");
  await page.getByRole("button",{name:"자료 목록에 보관 · 이 탭",exact:true}).click();
  await page.getByRole("navigation",{name:"프로젝트 업무"}).getByRole("link",{name:"외부 공유",exact:true}).click();
  await page.getByRole("textbox",{name:"수신자 표시 이름",exact:true}).fill("감리 초안");
  await page.getByRole("combobox",{name:/외부 역할/}).selectOption("request");
  await page.getByLabel("만료일",{exact:true}).fill("2099-01-01");
  await page.getByRole("checkbox",{name:/초대 범위 회의록/}).check();
  await page.getByRole("navigation",{name:"프로젝트 업무"}).getByRole("link",{name:"검토",exact:true}).click();
  await page.getByRole("navigation",{name:"프로젝트 업무"}).getByRole("link",{name:"외부 공유",exact:true}).click();
  await expect(page.getByRole("textbox",{name:"수신자 표시 이름",exact:true})).toHaveValue("감리 초안");
  await page.reload();
  await expect(page.getByRole("combobox",{name:/외부 역할/})).toHaveValue("request");
  await expect(page.getByLabel("만료일",{exact:true})).toHaveValue("2099-01-01");
  await expect(page.getByRole("checkbox",{name:/초대 범위 회의록/})).toBeChecked();
  await expect(page.getByRole("link",{name:"외부 참여자 화면 체험",exact:true})).toHaveCount(0);
  await page.evaluate(()=>{
    const key="1hk:preview:resources:00000000-0000-4000-8000-000000000101";
    const rows=JSON.parse(sessionStorage.getItem(key));rows[0].note="선택 이후 변경된 설명";sessionStorage.setItem(key,JSON.stringify(rows));
  });
  await page.reload();
  await expect(page.getByRole("alert")).toContainText("자료가 변경되거나 없어졌습니다");
  await expect(page.getByRole("button",{name:"공유 범위 고정 · 이 탭에 보관",exact:true})).toBeDisabled();
  await page.getByRole("button",{name:"선택 범위 다시 지정",exact:true}).click();
  await page.getByRole("checkbox",{name:/초대 범위 회의록/}).check();
  await page.getByRole("button",{name:"공유 범위 고정 · 이 탭에 보관",exact:true}).click();
  await expect(page.getByRole("link",{name:"외부 참여자 화면 체험",exact:true})).toHaveCount(1);
  await page.reload();
  await expect(page.getByRole("textbox",{name:"수신자 표시 이름",exact:true})).toHaveValue("");
  await expect(page.getByRole("link",{name:"외부 참여자 화면 체험",exact:true})).toHaveCount(1);
  await page.evaluate(()=>{
    const original=Storage.prototype.setItem;
    window.restoreDraftWrite=()=>{Storage.prototype.setItem=original;};
    Storage.prototype.setItem=function(key,value){if(key.startsWith("1hk:preview:sharing-draft:"))throw new DOMException("test quota","QuotaExceededError");return original.call(this,key,value);};
  });
  await page.getByRole("textbox",{name:"수신자 표시 이름",exact:true}).fill("보관 실패 후 초안");
  await expect(page.getByRole("alert")).toContainText("초대 초안을 보관하지 못했습니다");
  await page.getByRole("navigation",{name:"프로젝트 업무"}).getByRole("link",{name:"검토",exact:true}).click();
  await page.getByRole("navigation",{name:"프로젝트 업무"}).getByRole("link",{name:"외부 공유",exact:true}).click();
  await expect(page.getByRole("textbox",{name:"수신자 표시 이름",exact:true})).toHaveValue("보관 실패 후 초안");
  await page.evaluate(()=>window.restoreDraftWrite());
  await page.getByRole("button",{name:"초대 초안 보관 다시 시도",exact:true}).click();
  await page.reload();
  await expect(page.getByRole("textbox",{name:"수신자 표시 이름",exact:true})).toHaveValue("보관 실패 후 초안");
  await page.evaluate(()=>sessionStorage.setItem("1hk:preview:sharing-draft:00000000-0000-4000-8000-000000000101","null"));
  await page.reload();
  await expect(page.getByRole("alert")).toContainText("초대 초안을 복원하지 못했습니다");
  await expect(page.getByRole("textbox",{name:"수신자 표시 이름",exact:true})).toBeDisabled();
  assert.equal(await page.evaluate(()=>sessionStorage.getItem("1hk:preview:sharing-draft:00000000-0000-4000-8000-000000000101")),"null");
  assert.deepEqual(errors,[]);
 }finally{await browser.close();}
});

test("shared PDF opens only the frozen page of the byte-matching source",{skip:!process.env.SHARING_PREVIEW_ORIGIN,timeout:60000},async()=>{
  const origin=new URL(process.env.SHARING_PREVIEW_ORIGIN);
  assert.ok(["localhost","127.0.0.1"].includes(origin.hostname));
  const pdf=await PDFDocument.create();pdf.addPage([600,400]);pdf.addPage([600,400]).drawText("SHARED PAGE TWO");
  const file={name:"shared-source.pdf",mimeType:"application/pdf",buffer:Buffer.from(await pdf.save())};
  const wrong=await PDFDocument.create();wrong.addPage();
  const browser=await chromium.launch({headless:true});
  try{
    const page=await browser.newPage();const errors=[];page.on("pageerror",e=>errors.push(e.message));
    const base=`${origin.origin}/workspace-preview?project=00000000-0000-4000-8000-000000000101`;
    await page.goto(`${base}&start=file`);
    await page.getByLabel("작업실에서 열 PDF 선택").setInputFiles(file);
    await page.getByRole("button",{name:"선택한 PDF 등록 방식 확인",exact:true}).click();
    await page.getByRole("button",{name:"등록 방식 확인 후 준비",exact:true}).click();
    await expect(page.getByRole("button",{name:"다음 페이지",exact:true})).toBeEnabled();
    await page.getByRole("button",{name:"다음 페이지",exact:true}).click();
    await page.getByRole("button",{name:"검토 화면 열기",exact:true}).click();
    await page.getByRole("button",{name:"문 위치 변경 체험",exact:true}).click();
    await page.getByRole("textbox",{name:/요청 내용/}).fill("두 번째 페이지만 공유");
    await page.getByRole("button",{name:"검토 요청",exact:true}).click();
    await expect(page.getByRole("heading",{name:"검토 대기",exact:true})).toBeVisible();
    await page.goto(`${base}&panel=project-sharing`);
    await page.getByRole("textbox",{name:"수신자 표시 이름",exact:true}).fill("감리 · 예시");
    await page.getByLabel("만료일",{exact:true}).fill("2099-01-01");
    await page.getByRole("checkbox",{name:/shared-source.pdf/}).check();
    await page.getByRole("button",{name:"공유 범위 고정 · 이 탭에 보관",exact:true}).click();
    await page.getByRole("link",{name:"외부 참여자 화면 체험",exact:true}).click();
    await page.getByRole("textbox",{name:"이름 예시",exact:true}).fill("감리 예시");
    await page.getByRole("textbox",{name:"소속 예시",exact:true}).fill("예시 회사");
    await page.getByRole("button",{name:"공유된 범위 열기",exact:true}).click();
    const picker=page.getByLabel("공유 원본 PDF 다시 선택",{exact:true});
    await picker.setInputFiles({...file,buffer:Buffer.from(await wrong.save())});
    await expect(page.getByRole("alert")).toContainText("공유 당시 원본과 다른 PDF");
    await expect(page.locator("canvas")).toHaveCount(0);
    await picker.setInputFiles({...file,name:"renamed-matching-source.pdf"});
    await expect(page.locator("canvas")).toBeVisible();
    await expect(page.getByLabel("PDF 2쪽",{exact:true})).toBeVisible();
    await expect(page.getByRole("button",{name:"자료 다음 페이지",exact:true})).toHaveCount(0);
    await expect(page.getByRole("button",{name:"자료 이전 페이지",exact:true})).toHaveCount(0);
    await expect(page.getByRole("navigation",{name:"프로젝트 업무",exact:true})).toHaveCount(0);
    await page.getByRole("button",{name:"검토 오버레이 변경 전후",exact:true}).click();
    await expect(page.getByRole("button",{name:"검토 오버레이 변경 전후",exact:true})).toHaveAttribute("aria-pressed","true");
    if(process.env.SHARING_PDF_SCREENSHOT)await page.screenshot({path:process.env.SHARING_PDF_SCREENSHOT,fullPage:true});
    assert.deepEqual(errors,[]);
  }finally{await browser.close();}
});

test("guest sees only selected shared resources and expired invitations show no content",{skip:!process.env.SHARING_PREVIEW_ORIGIN,timeout:60000},async()=>{
  const origin=new URL(process.env.SHARING_PREVIEW_ORIGIN);
  assert.ok(["localhost","127.0.0.1"].includes(origin.hostname));
  const browser=await chromium.launch({headless:true});
  try{
    const page=await browser.newPage();
    const errors=[];page.on("pageerror",e=>errors.push(e.message));
    const project="00000000-0000-4000-8000-000000000101";
    const base=`${origin.origin}/workspace-preview?project=${project}`;
    await page.goto(`${base}&panel=project-resources`);
    for(const [name,note] of [["공유 회의록","공유 대상 설명"],["내부 전용 견적서","보이지 않아야 하는 내용"]]){
      await expect(page.getByRole("textbox",{name:"자료 이름",exact:true})).toBeEnabled();
      await page.getByRole("textbox",{name:"자료 이름",exact:true}).fill(name);
      await page.getByRole("textbox",{name:"자료 설명",exact:true}).fill(note);
      await page.getByRole("button",{name:"자료 목록에 보관 · 이 탭",exact:true}).click();
      await expect(page.getByRole("textbox",{name:"자료 이름",exact:true})).toHaveValue("");
    }
    await page.goto(`${base}&panel=project-sharing`);
    await expect(page.getByRole("textbox",{name:"수신자 표시 이름",exact:true})).toBeEnabled();
    await page.getByRole("textbox",{name:"수신자 표시 이름",exact:true}).fill("발주 담당 · 예시");
    await page.getByLabel("만료일",{exact:true}).fill("2099-01-01");
    await page.getByRole("checkbox",{name:/공유 회의록/}).check();
    await page.getByRole("button",{name:"공유 범위 고정 · 이 탭에 보관",exact:true}).click();
    await page.getByRole("link",{name:"외부 참여자 화면 체험",exact:true}).click();
    await expect(page.getByRole("heading",{name:"외부 참여자 화면",exact:true})).toBeVisible();
    const guestUrl=page.url();
    assert.ok(new URL(guestUrl).searchParams.get("guest"));
    await expect(page.getByRole("navigation",{name:"프로젝트 업무",exact:true})).toHaveCount(0);
    await expect(page.getByText("공유 대상 설명",{exact:true})).toHaveCount(0);
    await page.getByRole("textbox",{name:"이름 예시",exact:true}).fill("예시 참여자");
    await page.getByRole("textbox",{name:"소속 예시",exact:true}).fill("예시 발주처");
    await page.getByRole("button",{name:"공유된 범위 열기",exact:true}).click();
    await expect(page.getByText("공유 대상 설명",{exact:true})).toBeVisible();
    await expect(page.getByText("보이지 않아야 하는 내용",{exact:true})).toHaveCount(0);
    await expect(page.getByRole("navigation",{name:"공유된 항목",exact:true}).getByRole("button")).toHaveCount(1);
    await expect(page.getByRole("textbox",{name:"선택한 항목에 수정 요청",exact:true})).toHaveCount(0);
    await page.goto(`${base}&panel=project-sharing&role=viewer`);
    await expect(page.getByText("보기 전용 · 외부 공유 구성을 만들 수 없습니다.",{exact:true})).toBeVisible();
    await expect(page.getByRole("textbox",{name:"수신자 표시 이름",exact:true})).toHaveCount(0);
    // Fault fixture confined to this disposable browser's own UI-created record.
    await page.evaluate(project=>{
      const key=`1hk:preview:sharing:${project}`;
      const records=JSON.parse(sessionStorage.getItem(key));
      records[0].expiresAt="2000-01-01T00:00:00Z";
      sessionStorage.setItem(key,JSON.stringify(records));
    },project);
    await page.goto(guestUrl);
    await expect(page.getByRole("alert")).toContainText("초대가 만료되었습니다");
    await expect(page.getByText("공유 대상 설명",{exact:true})).toHaveCount(0);
    await expect(page.getByRole("textbox",{name:"이름 예시",exact:true})).toHaveCount(0);
    assert.deepEqual(errors,[]);
  }finally{await browser.close();}
});

test("guest drawing request returns through the same internal issue and status",{skip:!process.env.SHARING_PREVIEW_ORIGIN,timeout:60000},async()=>{
  const origin=new URL(process.env.SHARING_PREVIEW_ORIGIN);
  assert.ok(["localhost","127.0.0.1"].includes(origin.hostname));
  const browser=await chromium.launch({headless:true});
  try{
    const page=await browser.newPage();
    const errors=[];page.on("pageerror",e=>errors.push(e.message));
    const base=`${origin.origin}/workspace-preview?project=00000000-0000-4000-8000-000000000101`;
    await page.goto(base);
    await page.getByRole("link",{name:"1층 평면도 작업실 열기",exact:true}).click();
    await page.getByRole("button",{name:"검토 화면 열기",exact:true}).click();
    await page.getByRole("button",{name:"문 위치 변경 체험",exact:true}).click();
    await page.getByRole("textbox",{name:/요청 내용/}).fill("외부 발주자 검토 요청");
    await page.getByRole("button",{name:"검토 요청",exact:true}).click();
    await expect(page.getByRole("heading",{name:"검토 대기",exact:true})).toBeVisible();
    const drawingUrl=page.url();
    await page.goto(`${base}&panel=project-sharing`);
    await page.getByRole("textbox",{name:"수신자 표시 이름",exact:true}).fill("발주자 · 예시");
    await page.getByRole("combobox",{name:"외부 역할",exact:true}).selectOption("request");
    await page.getByLabel("만료일",{exact:true}).fill("2099-01-01");
    await page.getByRole("checkbox",{name:/1층 평면도/}).check();
    await page.getByRole("button",{name:"공유 범위 고정 · 이 탭에 보관",exact:true}).click();
    await page.getByRole("link",{name:"외부 참여자 화면 체험",exact:true}).click();
    await expect(page.getByRole("heading",{name:"외부 참여자 화면",exact:true})).toBeVisible();
    const guestUrl=page.url();
    const enter=async()=>{
      await page.getByRole("textbox",{name:"이름 예시",exact:true}).fill("발주자 예시");
      await page.getByRole("textbox",{name:"소속 예시",exact:true}).fill("발주처 예시");
      await page.getByRole("button",{name:"공유된 범위 열기",exact:true}).click();
    };
    await enter();
    const template=page.getByRole("img",{name:/1층 평면도 · 사무실 템플릿 이미지 예시/});
    await expect(template).toBeVisible();
    await expect.poll(()=>template.evaluate(image=>image.naturalWidth)).toBeGreaterThan(0);
    await page.getByRole("textbox",{name:"선택한 항목에 수정 요청",exact:true}).fill("출입구 유효폭을 확인해 주세요");
    await page.getByRole("button",{name:"수정 요청 보관 · 예시",exact:true}).click();
    const panel=page.getByRole("region",{name:"수정 요청 목록",exact:true});
    await expect(panel).toContainText("처리 상태: 대기");
    const requestRow=panel.locator('[data-request-id]').first();
    const id=await requestRow.getAttribute('data-request-id');assert.match(id,/^[0-9a-f-]{36}$/);
    await expect(requestRow.getByText(`요청 ID · ${id}`,{exact:true})).toBeHidden();
    const details=requestRow.getByText('요청 상세 정보',{exact:true});
    await details.focus();await page.keyboard.press('Enter');
    await expect(requestRow.getByText(`요청 ID · ${id}`,{exact:true})).toBeVisible();
    await details.click();
    await page.goto(drawingUrl);
    const internal=page.getByRole("region",{name:"수정 요청 목록",exact:true});
    await expect(internal).toContainText(id);
    await expect(internal).toContainText("출입구 유효폭을 확인해 주세요");
    await internal.getByRole("combobox",{name:"처리 상태",exact:true}).selectOption("resolved");
    await expect(internal.getByRole("button",{name:"답변과 상태 보관 · 예시",exact:true})).toBeDisabled();
    await internal.getByRole("textbox",{name:"처리 답변",exact:true}).fill("검토 도면의 출입구 유효폭 확인을 마쳤습니다.");
    const reviewBefore=await page.evaluate(()=>sessionStorage.getItem("1hk:preview:review:00000000-0000-4000-8000-000000000111"));
    assert.ok(reviewBefore);
    await internal.getByRole("link",{name:"요청 당시 도면·위치 보기",exact:true}).click();
    await expect(page.getByRole("heading",{name:"요청 당시 도면",exact:true})).toBeVisible();
    await expect(page.getByRole("main",{name:"요청 당시 도면 문맥",exact:true})).toContainText(id);
    await expect(page.getByRole("region",{name:"공유된 도면 읽기 전용",exact:true})).toContainText("R1 · 1쪽");
    await expect(page.getByRole("button",{name:"문 위치 변경 체험",exact:true})).toHaveCount(0);
    const requestWorkspaceUrl=page.url();
    if(process.env.REQUEST_WORKSPACE_SCREENSHOT)await page.screenshot({path:process.env.REQUEST_WORKSPACE_SCREENSHOT,fullPage:true});
    await page.getByRole("link",{name:"현재 편집본에서 수정",exact:true}).click();
    await expect(page.getByRole("heading",{name:"검토 대기",exact:true})).toBeVisible();
    assert.equal(new URL(page.url()).searchParams.get("externalFocus"),id);
    await expect(page.locator(`#external-request-${id}`)).toBeFocused();
    await internal.getByRole("link",{name:"요청 당시 도면·위치 보기",exact:true}).click();
    await page.getByRole("link",{name:"요청 목록으로 돌아가기",exact:true}).click();
    await expect(page.getByRole("heading",{name:"외부 공유 준비",exact:true})).toBeVisible();
    await expect(internal.getByRole("textbox",{name:"처리 답변",exact:true})).toHaveValue("검토 도면의 출입구 유효폭 확인을 마쳤습니다.");
    await expect(page.locator(`#external-request-${id}`)).toBeFocused();
    assert.equal(await page.evaluate(()=>sessionStorage.getItem("1hk:preview:review:00000000-0000-4000-8000-000000000111")),reviewBefore);
    await page.goto(drawingUrl);
    await page.reload();
    await expect(internal.getByRole("textbox",{name:"처리 답변",exact:true})).toHaveValue("검토 도면의 출입구 유효폭 확인을 마쳤습니다.");
    await expect(internal.getByRole("combobox",{name:"처리 상태",exact:true})).toHaveValue("resolved");
    await internal.getByRole("button",{name:"답변과 상태 보관 · 예시",exact:true}).click();
    await expect(internal).toContainText("처리 상태: 해결");
    await expect(page.getByRole("heading",{name:"검토 대기",exact:true})).toBeVisible();
    await page.goto(`${requestWorkspaceUrl}&role=viewer`);
    await expect(page.getByRole("link",{name:"현재 도면 보기",exact:true})).toBeVisible();
    await expect(page.getByRole("textbox",{name:"처리 답변",exact:true})).toHaveCount(0);
    const wrongRequestUrl=new URL(requestWorkspaceUrl);wrongRequestUrl.searchParams.set("screenDocument","00000000-0000-4000-8000-000000000112");
    await page.goto(wrongRequestUrl.href);
    await expect(page.getByRole("alert")).toContainText("다른 도면으로 대신 열지 않았습니다");
    await expect(page.getByRole("region",{name:"공유된 도면 읽기 전용",exact:true})).toHaveCount(0);
    await page.goto(guestUrl);await enter();
    await expect(panel).toContainText(id);
    await expect(panel).toContainText("처리 상태: 해결");
    await expect(panel.getByRole("list",{name:"처리 답변 이력",exact:true})).toContainText("검토 도면의 출입구 유효폭 확인을 마쳤습니다.");
    await expect(panel.getByRole("combobox")).toHaveCount(0);
    await page.setViewportSize({width:390,height:844});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false,"guest reply should fit a narrow screen");
    if(process.env.SHARING_PREVIEW_SCREENSHOT)await page.screenshot({path:process.env.SHARING_PREVIEW_SCREENSHOT,fullPage:true});
    await page.setViewportSize({width:1280,height:900});
    await page.goto(drawingUrl);
    await page.getByRole("button",{name:"검토자 보기",exact:true}).click();
    await page.getByRole("textbox",{name:"D01 위치에 수정 의견",exact:true}).fill("내부 검토: 피난 동선을 재확인해 주세요");
    await page.getByRole("button",{name:"수정 요청",exact:true}).click();
    await page.getByRole("button",{name:"작성자 보기",exact:true}).click();
    const internalIssue=internal.getByRole("article",{name:"내부 수정 요청",exact:true});
    await expect(internalIssue).toContainText("처리 상태: 대기");
    await expect(internal).toContainText("출입구 유효폭을 확인해 주세요");
    const issueId=await internalIssue.getAttribute("data-request-id");assert.ok(issueId);
    await internalIssue.getByRole("button",{name:/의견 위치 보기/}).click();
    await page.getByRole("button",{name:"의견 반영 · 문 위치 재조정",exact:true}).click();
    await expect(internalIssue).toContainText("처리 상태: 처리 중");
    await expect(internalIssue).toHaveAttribute("data-request-id",issueId);
    await page.getByRole("button",{name:"재검토 요청",exact:true}).click();
    await page.getByRole("button",{name:"검토자 보기",exact:true}).click();
    await page.getByRole("button",{name:"변경 전후 확인",exact:true}).click();
    await page.getByRole("button",{name:"검토 완료 · 승인 요청",exact:true}).click();
    await page.getByRole("button",{name:"승인자 보기",exact:true}).click();
    await page.getByRole("button",{name:"변경 전후 확인",exact:true}).click();
    await page.getByRole("button",{name:"최종 승인하기",exact:true}).click();
    await expect(internalIssue).toContainText("처리 상태: 해결");
    await page.goto(`${base}&panel=project-reviews`);
    await expect(internalIssue).toHaveAttribute("data-request-id",issueId);
    await expect(internalIssue).toContainText("처리 상태: 해결");
    await expect(internal).toContainText(id);
    if(process.env.UNIFIED_REQUEST_SCREENSHOT)await page.screenshot({path:process.env.UNIFIED_REQUEST_SCREENSHOT,fullPage:true,animations:"disabled"});
    await page.goto(guestUrl);await enter();
    await expect(panel).not.toContainText("내부 검토: 피난 동선을 재확인해 주세요");
    assert.deepEqual(errors,[]);
  }finally{await browser.close();}
});

test("guest request drafts stay with their selected resource after switching and reopening",{skip:!process.env.SHARING_PREVIEW_ORIGIN,timeout:60000},async()=>{
  const origin=new URL(process.env.SHARING_PREVIEW_ORIGIN);
  assert.ok(["localhost","127.0.0.1"].includes(origin.hostname));
  const browser=await chromium.launch({headless:true});
  try{
    const page=await browser.newPage();
    const errors=[];page.on("pageerror",e=>errors.push(e.message));
    const base=`${origin.origin}/workspace-preview?project=00000000-0000-4000-8000-000000000101`;
    await page.goto(`${base}&panel=project-resources`);
    for(const name of ["회의록 A","시방서 B"]){
      await page.getByRole("textbox",{name:"자료 이름",exact:true}).fill(name);
      await page.getByRole("button",{name:"자료 목록에 보관 · 이 탭",exact:true}).click();
      await expect(page.getByRole("textbox",{name:"자료 이름",exact:true})).toHaveValue("");
    }
    await page.goto(`${base}&panel=project-sharing`);
    await page.getByRole("textbox",{name:"수신자 표시 이름",exact:true}).fill("초안 검증 · 예시");
    await page.getByRole("combobox",{name:"외부 역할",exact:true}).selectOption("request");
    await page.getByLabel("만료일",{exact:true}).fill("2099-01-01");
    await page.getByRole("checkbox",{name:/회의록 A/}).check();
    await page.getByRole("checkbox",{name:/시방서 B/}).check();
    await page.getByRole("button",{name:"공유 범위 고정 · 이 탭에 보관",exact:true}).click();
    await page.getByRole("link",{name:"외부 참여자 화면 체험",exact:true}).click();
    const enter=async()=>{
      await page.getByRole("textbox",{name:"이름 예시",exact:true}).fill("참여자 예시");
      await page.getByRole("textbox",{name:"소속 예시",exact:true}).fill("감리 예시");
      await page.getByRole("button",{name:"공유된 범위 열기",exact:true}).click();
    };
    await enter();
    const input=page.getByRole("textbox",{name:"선택한 항목에 수정 요청",exact:true});
    const nav=page.getByRole("navigation",{name:"공유된 항목",exact:true});
    await input.fill("회의록의 참석자를 확인해 주세요");
    await nav.getByRole("button",{name:/시방서 B/}).click();
    await expect(input).toHaveValue("");
    await input.fill("시방서의 재료 기준을 확인해 주세요");
    await nav.getByRole("button",{name:/회의록 A/}).click();
    await expect(input).toHaveValue("회의록의 참석자를 확인해 주세요");
    await page.reload();await enter();
    await expect(input).toHaveValue("회의록의 참석자를 확인해 주세요");
    await page.getByRole("button",{name:"수정 요청 보관 · 예시",exact:true}).click();
    await expect(input).toHaveValue("");
    await page.reload();await enter();
    await expect(input).toHaveValue("");
    await expect(page.getByText(/요청 ID · /)).toHaveCount(1);
    await nav.getByRole("button",{name:/시방서 B/}).click();
    await expect(input).toHaveValue("시방서의 재료 기준을 확인해 주세요");
    // Simulate a quota failure only for this disposable browser's request drafts.
    await page.evaluate(()=>{
      window.restoreDraftWrites=Storage.prototype.setItem;
      Storage.prototype.setItem=function(key,value){
        if(key.startsWith("1hk:preview:external-request-draft:"))throw new DOMException("Test quota","QuotaExceededError");
        return window.restoreDraftWrites.call(this,key,value);
      };
    });
    await input.fill("보관 실패 중에도 유지할 시방서 의견");
    await expect(page.getByRole("alert")).toContainText("초안을 보관하지 못했습니다");
    await nav.getByRole("button",{name:/회의록 A/}).click();
    await expect(input).toHaveValue("");
    await nav.getByRole("button",{name:/시방서 B/}).click();
    await expect(input).toHaveValue("보관 실패 중에도 유지할 시방서 의견");
    await page.evaluate(()=>{Storage.prototype.setItem=window.restoreDraftWrites;delete window.restoreDraftWrites;});
    await page.getByRole("button",{name:"초안 보관 다시 시도",exact:true}).click();
    await expect(page.getByRole("alert")).toHaveCount(0);
    await page.reload();await enter();
    await nav.getByRole("button",{name:/시방서 B/}).click();
    await expect(input).toHaveValue("보관 실패 중에도 유지할 시방서 의견");
    // Invalid but parseable tab data must not be silently replaced by an empty draft.
    const damagedKey=await page.evaluate(()=>{
      const key=Object.keys(sessionStorage).find(key=>key.startsWith("1hk:preview:external-request-draft:")&&JSON.parse(sessionStorage.getItem(key)).message==="보관 실패 중에도 유지할 시방서 의견");
      sessionStorage.setItem(key,"false");return key;
    });
    await page.reload();await enter();
    await nav.getByRole("button",{name:/시방서 B/}).click();
    await expect(page.getByRole("alert")).toContainText("작성 초안을 복원하지 못했습니다");
    await expect(input).toBeDisabled();
    assert.equal(await page.evaluate(key=>sessionStorage.getItem(key),damagedKey),"false");
    assert.deepEqual(errors,[]);
  }finally{await browser.close();}
});
