import assert from 'node:assert/strict';
import test from 'node:test';
import {createServer} from 'vite';
const vite=await createServer({configFile:false,appType:'custom',logLevel:'silent',server:{middlewareMode:true}});
test.after(()=>vite.close());
test('local material events bind approved quantity and keep ordered received installed distinct',async()=>{
 const {recordMaterialEvent,materialTotals,validMaterialHistory}=await vite.ssrLoadModule('/app/lukas/lib/workflow-document-materials.ts');
 const doc={id:'d',title:'d',shapes:[],quantityReviews:[{sequence:1,phase:'approved',revision:1,items:[{id:'wall',quantity:{raw:10,correction:2,unit:'m'}}]}]};
 const input={sequence:1,objectId:'wall',kind:'order',amount:12,reason:'발주 계획'};
 let next=recordMaterialEvent(doc,'author',input);assert.equal(next.materialEvents.length,1);assert.equal(doc.materialEvents,undefined);
 assert.equal(recordMaterialEvent(doc,'viewer',input),doc);
 assert.equal(recordMaterialEvent(doc,'author',{...input,kind:'receive'}),doc);
 assert.equal(recordMaterialEvent(doc,'author',{...input,sequence:2}),doc);
 assert.equal(recordMaterialEvent({...doc,quantityReviews:[{...doc.quantityReviews[0],phase:'reviewed'}]},'author',input).materialEvents,undefined);
 assert.equal(recordMaterialEvent(next,'author',{...input,kind:'receive',amount:13}),next);
 next=recordMaterialEvent(next,'author',{...input,kind:'receive',amount:8});
 next=recordMaterialEvent(next,'author',{...input,kind:'install',amount:5});
 assert.deepEqual(materialTotals(next,1,'wall'),{order:12,receive:8,install:5});
 assert.equal(recordMaterialEvent(next,'author',{...input,kind:'install',amount:4}),next);
 assert.equal(recordMaterialEvent(next,'author',{...input,amount:-1}),next);
 assert.equal(recordMaterialEvent(next,'author',{...input,reason:''}),next);
 assert.deepEqual(materialTotals(next,2,'wall'),{order:0,receive:0,install:0});
 assert.equal(validMaterialHistory(next),true);
 assert.equal(validMaterialHistory({...next,quantityReviews:[]}),false);
 assert.equal(validMaterialHistory({...next,materialEvents:[next.materialEvents[1]]}),false);
 assert.equal(recordMaterialEvent(next,'author',{...input,kind:'cancel-order',amount:5}),next);
 assert.equal(recordMaterialEvent(next,'author',{...input,kind:'return',amount:4}),next);
 next=recordMaterialEvent(next,'author',{...input,kind:'uninstall',amount:2,reason:'설치 위치 수정'});
 next=recordMaterialEvent(next,'author',{...input,kind:'return',amount:5,reason:'미설치 자재 반품'});
 next=recordMaterialEvent(next,'author',{...input,kind:'cancel-order',amount:9,reason:'잔량 취소'});
 assert.deepEqual(materialTotals(next,1,'wall'),{order:3,receive:3,install:3});
 assert.equal(validMaterialHistory(next),true);
 assert.equal(recordMaterialEvent(next,'author',{...input,kind:'uninstall',amount:4}),next);
 assert.equal(next.materialEvents.length,6);
});
test('dated orders track linked receipts independently and reject invalid dates or excess receipts',async()=>{
 const m=await vite.ssrLoadModule('/app/lukas/lib/workflow-document-materials.ts');const doc={id:'d',title:'d',shapes:[],quantityReviews:[{sequence:1,phase:'approved',items:[{id:'wall'}]}]};
 const order={sequence:1,objectId:'wall',kind:'order',amount:10,reason:'발주',recordedOn:'2026-09-01',expectedOn:'2026-09-10',supplier:'공급처 A'};
 let next=m.recordMaterialEvent(doc,'author',order);assert.equal(next.materialEvents[0].supplier,'공급처 A');
 assert.equal(m.recordMaterialEvent(doc,'author',{...order,expectedOn:'2026-02-30'}),doc);assert.equal(m.recordMaterialEvent(doc,'author',{...order,expectedOn:'2026-08-31'}),doc);
 next=m.recordMaterialEvent(next,'author',{...order,amount:20,supplier:'공급처 B'});
 const receive={sequence:1,objectId:'wall',kind:'receive',amount:6,reason:'A 입고',orderId:1};next=m.recordMaterialEvent(next,'author',receive);
 assert.equal(m.recordMaterialEvent(next,'author',{...receive,amount:5}),next);assert.equal(m.recordMaterialEvent(next,'author',{...receive,orderId:999}),next);
 assert.deepEqual(m.materialOrderTotals(next,1),{order:10,receive:6,install:0});assert.deepEqual(m.materialOrderTotals(next,2),{order:20,receive:0,install:0});
 assert.equal(m.materialOrderDue(next,1,'2026-09-11'),'late');assert.equal(m.materialOrderDue(next,1,'2026-09-10'),'due');
 next=m.recordMaterialEvent(next,'author',{...receive,amount:4});assert.equal(m.materialOrderDue(next,1,'2026-09-11'),'received');assert.equal(m.validMaterialHistory(next),true);
});
