import test from 'node:test';import assert from 'node:assert/strict';import {createServer} from 'vite';
test('handover requires approved asset/inspection evidence and preserves recipient correction snapshots',async()=>{
 const vite=await createServer({configFile:false,appType:'custom',logLevel:'silent',server:{middlewareMode:true}});try{
  const m=await vite.ssrLoadModule('/app/lukas/lib/workflow-handover.ts'),{reduceDocumentReview}=await vite.ssrLoadModule('/app/lukas/lib/workflow-document-review.ts'),{addDocumentFieldNote}=await vite.ssrLoadModule('/app/lukas/lib/workflow-document-field.ts'),{recordInspection}=await vite.ssrLoadModule('/app/lukas/lib/workflow-inspections.ts');
  let doc={id:'handover',title:'준공 도면',source:{name:'asset.pdf',sha256:'b'.repeat(64),pages:1},shapes:[{id:'pump',label:'펌프',x:10,y:20},{id:'pipe',label:'배관',x:30,y:40}]};
  const asset={objectId:'pump',code:'P-01',name:'급수 펌프',location:'기계실',manufacturer:'제조사 예시',model:'M-10',manual:'운전 매뉴얼 v1',warrantyEnd:'2027-09-30',maintenanceContact:'시설팀',maintenancePlan:'분기별 작동 점검'};
  assert.equal(m.saveAsset(doc,'viewer',asset),doc);doc=m.saveAsset(doc,'author',asset);
  assert.equal(doc.assetRegister[0].warrantyEnd,'2027-09-30');
  assert.equal(m.saveAsset(doc,'author',{...asset,warrantyEnd:'2027-02-30'}),doc);
  assert.equal(m.saveAsset(doc,'author',{...asset,objectId:'pipe',code:'p-01'}),doc);
  assert.equal(m.prepareHandover(doc,'author',1,'시설관리자'),doc);
  for(const [role,type]of[['author','request'],['reviewer','review'],['approver','approve']])doc=reduceDocumentReview(doc,role,{type,targetId:'pump',message:'준공 도면 확인'});
  assert.equal(m.prepareHandover(doc,'author',1,'시설관리자'),doc);
  doc=addDocumentFieldNote(doc,'pump','author',{title:'펌프 점검',note:'설치 확인',location:'기계실',condition:'conforming'});
  doc=recordInspection(doc,1,'reviewer','inspect',{note:'점검 종결',checks:['pass','pass','na']});
  const partial=m.saveAsset(doc,'author',{...asset,objectId:'pipe',code:'P-02'});
  assert.equal(m.prepareHandover(partial,'author',1,'시설관리자'),partial);
  assert.equal(m.prepareHandover(partial,'author',1,'시설관리자',undefined,[]),partial);
  assert.equal(m.prepareHandover(partial,'author',1,'시설관리자',undefined,['missing']),partial);
  assert.equal(m.prepareHandover(partial,'author',1,'시설관리자',undefined,['pump','pump']),partial);
  assert.equal(m.prepareHandover(partial,'author',1,'시설관리자',undefined,['pump']).handovers[0].assets.length,1);
  let current=m.prepareHandover(doc,'author',1,'시설관리자');assert.equal(current.handovers[0].assets.length,1);
  assert.equal(current.handovers[0].assets[0].inspection.events.length,1);
  assert.equal(m.decideHandover(current,1,'author','received','확인'),current);
  current=m.decideHandover(current,1,'recipient','changes','매뉴얼 표기 보완');
  current=m.saveAsset(current,'author',{...asset,manual:'운전 매뉴얼 v2'});
  assert.equal(current.handovers[0].assets[0].manual,'운전 매뉴얼 v1');
  assert.equal(current.handovers[0].assets[0].maintenancePlan,'분기별 작동 점검');
  const manual={name:'manual.txt',size:12,sha256:'c'.repeat(64)};
  const withManual=m.saveAsset(current,'author',{...asset,manualFiles:[manual]});
  assert.deepEqual(withManual.assetRegister[0].manualFiles,[manual]);
  const manualPackage=m.prepareHandover(withManual,'author',1,'시설관리자',1);
  assert.equal(m.decideHandover(manualPackage,2,'recipient','received','확인'),manualPackage);
  assert.equal(m.decideHandover(manualPackage,2,'recipient','received','확인',['d'.repeat(64)]),manualPackage);
  assert.equal(m.decideHandover(manualPackage,2,'recipient','received','확인',[manual.sha256]).handovers[1].phase,'received');
  current=m.prepareHandover(current,'author',1,'시설관리자',1);assert.equal(current.handovers[1].previous,1);
  current=m.decideHandover(current,2,'recipient','received','인계본 확인');
  assert.equal(current.handovers[0].phase,'changes');assert.equal(current.handovers[1].phase,'received');
  assert.equal(m.prepareHandover(current,'author',1,'시설관리자',1),current);
  assert.equal(m.setAssetArchived(current,'viewer','pump',true),current);
  assert.equal(m.setAssetArchived(current,'author','missing',true),current);
  const archived=m.setAssetArchived(current,'author','pump',true);
  assert.equal(archived.assetRegister[0].archived,true);assert.deepEqual(archived.handovers,current.handovers);
  assert.equal(m.handoverReadiness(archived,1).rows.length,0);
  assert.equal(m.prepareHandover(archived,'author',1,'시설관리자'),archived);
  assert.equal(m.saveAsset(archived,'author',asset),archived);
  const restored=m.setAssetArchived(archived,'author','pump',false);
  assert.equal(m.handoverReadiness(restored,1).rows.length,1);assert.deepEqual(restored.handovers,current.handovers);
  const codec=await vite.ssrLoadModule('/app/lukas/lib/workflow-prototype-session.ts'),{createWorkflow}=await vite.ssrLoadModule('/app/lukas/lib/workflow-prototype.ts');
  const raw=codec.encodeWorkflowSession({scenarios:Object.fromEntries(['architecture','ifc','civil'].map(s=>[s,createWorkflow(s)])),drafts:{},blankDocuments:[current]});
  assert.deepEqual(codec.decodeWorkflowSession(raw).blankDocuments[0].handovers,current.handovers);
 }finally{await vite.close();}
});
